/* Generated By:JavaCC: Do not edit this line. CalculatorConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VAR = 1;
  /** RegularExpression Id. */
  int DECIMAL = 2;
  /** RegularExpression Id. */
  int BINARIO = 3;
  /** RegularExpression Id. */
  int OCTAL = 4;
  /** RegularExpression Id. */
  int ID = 5;
  /** RegularExpression Id. */
  int EOL = 6;
  /** RegularExpression Id. */
  int TRUE = 7;
  /** RegularExpression Id. */
  int FALSE = 8;
  /** RegularExpression Id. */
  int MENOR = 9;
  /** RegularExpression Id. */
  int MAYOR = 10;
  /** RegularExpression Id. */
  int IGUAL = 11;
  /** RegularExpression Id. */
  int SUMA = 12;
  /** RegularExpression Id. */
  int RESTA = 13;
  /** RegularExpression Id. */
  int MULTI = 14;
  /** RegularExpression Id. */
  int DIV = 15;
  /** RegularExpression Id. */
  int AND = 16;
  /** RegularExpression Id. */
  int OR = 17;
  /** RegularExpression Id. */
  int NOT = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"var\"",
    "<DECIMAL>",
    "<BINARIO>",
    "<OCTAL>",
    "<ID>",
    "\"\\n\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"if\"",
    "\"else\"",
  };

}
